# Generated by Django 4.1.7 on 2023-03-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('block_title',)},
        ),
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ('memo_title',)},
        ),
        migrations.AlterField(
            model_name='block',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='memo_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
